### ISSUE TITLE
superscript letters are not rendered

### ISSUE THREAD

**Issue by vks** [dylanede/rusttype#1]
Rendering `E = mc²` in the example works, but `E = mcⁿ` does not. (The superscript `n` is not rendered. It is rendered correctly in LibreOffice.)

**Comment by dylanede** [comment]
That's because Gudea Regular, the font supplied with the example, does not support the character `ⁿ`, U+207F. If you try the same with this font in LibreOffice, chances are that it will substitute the missing glyph from another font (like Arial). Gudea Regular only has 278 characters defined. I picked it for distribution with the example because it is very small, only 22KB. You can try swapping it out for a font supporting more characters.

Since this is not actually a problem with RustType, I'm closing this. Thanks for the feedback though, and if you encounter any other issues please report them.

**Comment by vks** [comment]
Shouldn't a placeholder character be rendered in this case?

**Comment by dylanede** [comment]
Yes, it should, and as far as I can tell, RustType is doing the right thing and returning glyph 0 for code points that are not defined in the font. Fonts should provide a placeholder like a square or other symbol for glyph 0. In this particular case it appears that Gudea Regular doesn't have any shape for glyph 0. I've tried this examples with more complete fonts (like DejaVu Sans), and the correct empty box glyph is shown for unsupported characters.

**Comment by dylanede** [comment]
Maybe this makes Gudea Regular not such a good choice for an example font. I'm not sure.

**Comment by vks** [comment]
Would it make sense for rusttype to return an error if the is no glyph 0?

**Comment by dylanede** [comment]
Well, technically there is a glyph 0. It just has no shape associated with it. This is perfectly legal. Really I think the best thing to do is expose a method like `has_shape` so that users can detect this (i.e. user code would specifically check whether glyph 0 has a shape, then if necessary account for there being no shape in whichever way is most appropriate for the application).
