### ISSUE TITLE
Avoid deref polymorphism

### ISSUE THREAD

**Issue by nrc** [dylanede/rusttype#4]
If you can, refactoring to avoid this anti-pattern would be good. It is not really idiomatic Rust and should be avoided where possible. [Here](https://github.com/nrc/patterns/blob/master/anti_patterns/deref.md)'s a little write up on why it is an anti-pattern.

Really exciting library, by the way!

**Comment by dylanede** [comment]
OK, so I'm looking at dealing with this now. I'm looking at replacing the `Deref` impls with explicit pass-through methods on each glyph type. One thing I'd like to do with this though is put these pass through methods in a trait, so that types containing a `Glyph` can be passed to functions that expect types implementing the trait for `Glyph` functions, etc. Trouble is, I can't think of good names for these traits. There's currently three glyph types: `Glyph`, `SizedGlyph` (soon to be renamed to `ScaledGlyph`) and `PositionedGlyph`. They would each need a corresponding trait (even `PositionedGlyph`, to remain extensible). One possibility is to rename the glyph types and give their current names to the traits. There's also the possibility of instead making the glyph types generic, taking the type they wrap as a parameter, but that could prove unwieldy for users (e.g. `Positioned<Scaled<Glyph>>`). It would however make the types more flexible, if, for example, another modifying type is made to be inserted in the hierarchy, e.g. `Positioned<Mirrored<Scaled<Glyph>>`. This could get complex fast though.

Thoughts?

**Comment by dylanede** [comment]
Or perhaps the trait idea is overkill. Any function that wants a raw `Glyph` can either take a reference that wrapping types can expose through a method, or since all glyph types are clone, the user can just `clone` the `&Glyph` returned by the accessor method before passing it to the function.

**Comment by dylanede** [comment]
Also, if there are going to be accessor methods to get the inner type, the naming of these things is not straightforward. For a `ScaledGlyph`, getting the `Glyph` might be called `unscaled`. But then for the same method for `PositionedGlyph`, should that be called `unscaled_and_unpositioned`, `unscaled`, or just not exist? Another issue: if `unscaled` returns `&Glyph`, then maybe there should also be `into_unscaled`, returning `Glyph`. Then maybe for symmetry that should mean that the `scaled` method on `Glyph` should in fact be `into_scaled`. But this is then unnecessarily verbose for the common use cases.

**Comment by nrc** [comment]
I'm not sure about the design re traits etc., but for naming, it sounds like you should rename `Glyph` to `BaseGlyph`, then you can always use `base()` rather than `unscaled`, etc.
