### ISSUE TITLE
unreachable code panic

### ISSUE THREAD

**Issue by Maxjen** [dylanede/rusttype#7]
I ran into an unreachable code panic when trying to use the DejaVuSans font with RustType. It pointed me to [this line](https://github.com/dylanede/stb_truetype-rs/blob/master/src/lib.rs#L369) from stb_truetype-rs.

Here is a slightly modified version of the example code to reproduce the panic:
[rusttype_test.zip](https://github.com/dylanede/rusttype/files/128893/rusttype_test.zip)

I also noticed that pair_kerning always returned 0.0 for all the glyph combinations I tried with the Gudea-Regular font. I was going to test if this was also the case with other fonts, but then I got the panic.

**Comment by dylanede** [comment]
Right, I see what the problem is. It's a slight mistake on my part when I translated the stb_truetype.h code to Rust. For some reason I put `unreachable!()` when I should have put `return 0`. So basically the requested character does not have a glyph in the font, and the undef glyph should have been returned. This bug is triggered when the font uses glyf table formats 12 or 13 (as apparently DejaVuSans does). I'll fix this and issue a patch release. Thanks for the report!

**Comment by dylanede** [comment]
You may need to `cargo update` to see the patch change.

**Comment by dylanede** [comment]
Regarding the kerning returning 0.0 for Gudea Regular, I believe that may just be because that font is very minimal. This really does need some more testing with other fonts though.

**Comment by Maxjen** [comment]
Okay, the panic is gone and I can use the DejaVuSans font now! But it seems the code I attached still crashes due to a different kerning related bug. I'll open another issue for that.
